### ISSUE TITLE
broken CSV generation

### ISSUE THREAD

**Issue by antoine-de** [openmaptiles/import-osmborder#3]
Hi, 

It seems that the CVS generation does not work anymore because of a change on [osmborder](https://github.com/pnorman/osmborder/).

They added an additional column [here](https://github.com/pnorman/osmborder/commit/201fc1b894900cdb51e2883dce84e0874de21454) leading to problems while importing.

To fix this, [this commit](https://github.com/pnorman/osmborder/commit/7ca2dd34399e3e5314a6b68e35f3e47d272de20b) seems the last valid one, but there might be cleaner way to solve this (a better way would be to handle this column in the import, but just adding the column in pgfutter does not seems to do the trick).

Thanks for the nice work on openmaptiles!

Antoine

**Comment by MartinMikita** [comment]
Thanks Antoine for your links to the commit!

We have fixed it and tested the generate and import process, and verified the results.
