### ISSUE TITLE
New docker release with updated borders

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/import-osmborder#5]
In the [latest release](https://github.com/openmaptiles/import-osmborder/releases/tag/v0.4), OSM Border generated CSV from the OSM planet file 2017-11-20.pbf

Would it be possible to create a new release with updated borders?

**Comment by ARolek** [comment]
I ran into this same issue a few days ago trying to get corrected maritime attributes for various OSM borders. In the end, I downloaded the OSM planet and generated a new osm borders CSV and container using this repo's generate/DockerFile and published it at https://hub.docker.com/r/gospatial/import-osmborder. 

It would be better to publish the updated data to this repository so a forked container is unnecessary. @eva-j if I was to post the new CSV on S3 could it be published to the repo's releases to match the current strategy?

**Comment by eva-j** [comment]
Definitely, I plan to update the data of import-osmborder (and other imports) before upcoming OMT release (next month).

**Comment by ARolek** [comment]
Ok. The CSV can be downloaded [here]( https://rolek-public.s3.amazonaws.com/open-map-tiles/osmborder_lines.csv.zip). The data is derived from a full planet PBF obtained on October 7, 2019.

**Comment by eva-j** [comment]
Docker image updated with data of 11th November 2019.
https://hub.docker.com/r/openmaptiles/import-osmborder

**Comment by ARolek** [comment]
Great! Thanks for the follow up.
